<?php
include "1.php";
mysqli_select_db($dbcn, "города_области");
$q1="CREATE TABLE історія (номер DOUBLE NOT NULL PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q1);
$q2="CREATE TABLE географія (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q2);
$q3="CREATE TABLE дніпро (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q3);
$q4="CREATE TABLE камянске (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q4);
$q5="CREATE TABLE кривийріг (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q5);
$q6="CREATE TABLE дніпропетровщина (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q6);
$q7="CREATE TABLE інформація_пер (імя VARCHAR(40) NOT NULL, назва VARCHAR(40) NOT NULL, адрес VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q7);
$q8="CREATE TABLE нікополь (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q8);
$q9="CREATE TABLE новомосковськ (id INT UNSIGNED UNIQUE AUTO_INCREMENT PRIMARY KEY,імя VARCHAR(40) NOT NULL, текст VARCHAR(4000) NOT NULL, зоб VARCHAR(40)) ENGINE=InnoDB DEFAULT CHARSET=cp1251";
mysqli_query($dbcn, $q9);
?>